# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import admvozgrpc_pb2 as admvozgrpc__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in admvozgrpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AdminServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IzbraniKraji = channel.unary_unary(
                '/admvoz.AdminService/IzbraniKraji',
                request_serializer=admvozgrpc__pb2.GetIzbraniKrajiRequest.SerializeToString,
                response_deserializer=admvozgrpc__pb2.IzbraniKrajiResponse.FromString,
                _registered_method=True)
        self.IzbraneStoritve = channel.unary_unary(
                '/admvoz.AdminService/IzbraneStoritve',
                request_serializer=admvozgrpc__pb2.GetIzbraneStoritveRequest.SerializeToString,
                response_deserializer=admvozgrpc__pb2.IzbraneStoritveResponse.FromString,
                _registered_method=True)
        self.IzbraniStatusi = channel.unary_unary(
                '/admvoz.AdminService/IzbraniStatusi',
                request_serializer=admvozgrpc__pb2.GetIzbraniStatusiRequest.SerializeToString,
                response_deserializer=admvozgrpc__pb2.IzbraniStatusiResponse.FromString,
                _registered_method=True)
        self.IzbranaVozila = channel.unary_unary(
                '/admvoz.AdminService/IzbranaVozila',
                request_serializer=admvozgrpc__pb2.GetIzbranaVozilaRequest.SerializeToString,
                response_deserializer=admvozgrpc__pb2.IzbranaVozilaResponse.FromString,
                _registered_method=True)
        self.IzbranaVozila1 = channel.unary_unary(
                '/admvoz.AdminService/IzbranaVozila1',
                request_serializer=admvozgrpc__pb2.GetIzbranaVozila1Request.SerializeToString,
                response_deserializer=admvozgrpc__pb2.IzbranaVozila1Response.FromString,
                _registered_method=True)


class AdminServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def IzbraniKraji(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IzbraneStoritve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IzbraniStatusi(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IzbranaVozila(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IzbranaVozila1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IzbraniKraji': grpc.unary_unary_rpc_method_handler(
                    servicer.IzbraniKraji,
                    request_deserializer=admvozgrpc__pb2.GetIzbraniKrajiRequest.FromString,
                    response_serializer=admvozgrpc__pb2.IzbraniKrajiResponse.SerializeToString,
            ),
            'IzbraneStoritve': grpc.unary_unary_rpc_method_handler(
                    servicer.IzbraneStoritve,
                    request_deserializer=admvozgrpc__pb2.GetIzbraneStoritveRequest.FromString,
                    response_serializer=admvozgrpc__pb2.IzbraneStoritveResponse.SerializeToString,
            ),
            'IzbraniStatusi': grpc.unary_unary_rpc_method_handler(
                    servicer.IzbraniStatusi,
                    request_deserializer=admvozgrpc__pb2.GetIzbraniStatusiRequest.FromString,
                    response_serializer=admvozgrpc__pb2.IzbraniStatusiResponse.SerializeToString,
            ),
            'IzbranaVozila': grpc.unary_unary_rpc_method_handler(
                    servicer.IzbranaVozila,
                    request_deserializer=admvozgrpc__pb2.GetIzbranaVozilaRequest.FromString,
                    response_serializer=admvozgrpc__pb2.IzbranaVozilaResponse.SerializeToString,
            ),
            'IzbranaVozila1': grpc.unary_unary_rpc_method_handler(
                    servicer.IzbranaVozila1,
                    request_deserializer=admvozgrpc__pb2.GetIzbranaVozila1Request.FromString,
                    response_serializer=admvozgrpc__pb2.IzbranaVozila1Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'admvoz.AdminService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('admvoz.AdminService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdminService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IzbraniKraji(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admvoz.AdminService/IzbraniKraji',
            admvozgrpc__pb2.GetIzbraniKrajiRequest.SerializeToString,
            admvozgrpc__pb2.IzbraniKrajiResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IzbraneStoritve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admvoz.AdminService/IzbraneStoritve',
            admvozgrpc__pb2.GetIzbraneStoritveRequest.SerializeToString,
            admvozgrpc__pb2.IzbraneStoritveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IzbraniStatusi(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admvoz.AdminService/IzbraniStatusi',
            admvozgrpc__pb2.GetIzbraniStatusiRequest.SerializeToString,
            admvozgrpc__pb2.IzbraniStatusiResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IzbranaVozila(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admvoz.AdminService/IzbranaVozila',
            admvozgrpc__pb2.GetIzbranaVozilaRequest.SerializeToString,
            admvozgrpc__pb2.IzbranaVozilaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IzbranaVozila1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admvoz.AdminService/IzbranaVozila1',
            admvozgrpc__pb2.GetIzbranaVozila1Request.SerializeToString,
            admvozgrpc__pb2.IzbranaVozila1Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
